version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - spring-mongo-network

  springboot:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    networks:
      - spring-mongo-network
    depends_on:
      - mongo

networks:
  spring-mongo-network:
